version: '3.8'

services:
  petrol-backend-utility:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: petrol_backend_util
    networks:
      - palyvo-network
  mongo1:
    image: mongo:4.4
    command: --replSet rs0
    networks:
      - palyvo-network
    ports:
      - 27017:27017
#  mongo2:
#    image: mongo:4.4
#    command: --replSet rs0
#    networks:
#      - palyvo-network
#    ports:
#      - 27018:27017
#  mongo3:
#    image: mongo:4.4
#    command: --replSet rs0
#    networks:
#      - palyvo-network
#    ports:
#      - 27019:27017
networks:
  palyvo-network: